"""End-to-end stylesheet tests through the real CSSProcessor: any OS with PyQt6."""

import os

import pytest

pytest.importorskip("PyQt6.QtWidgets", reason="core.config imports PyQt6")

from core.utils.css_processor import CSSProcessor  # noqa: E402

PALETTE_CSS = """\
/* This file is automatically generated by YASB wallpaper watcher */
:root {
    --wallpaper-color-1: #1a2b3c;
    --wallpaper-color-1-rgb: 26, 43, 60;
    --wallpaper-accent: #ff8800;
    --wallpaper-text: #ffffff;
}

/* Auto-apply: recolor the bar from the wallpaper palette */
.yasb-bar {
    background-color: #1a2b3c;
    color: #ffffff;
}
"""


def _write(path, content):
    path.write_text(content, encoding="utf-8")
    return str(path)


def test_generated_css_processed_verbatim(tmp_path, monkeypatch):
    styles = _write(tmp_path / "styles.css", ".clock-widget { color: white; }\n")
    monkeypatch.setattr("core.config.load_generated_css", lambda: PALETTE_CSS)

    processor = CSSProcessor(styles)
    css = processor.process()

    assert "background-color: #1a2b3c;" in css
    assert "color: #ffffff;" in css
    # Literal hex means Qt never sees an unresolved variable.
    assert "var(--wallpaper" not in css


def test_imported_palette_file_resolves(tmp_path, monkeypatch):
    palette_path = _write(tmp_path / "yasb_wallpaper_colors.css", PALETTE_CSS)
    styles = _write(tmp_path / "styles.css", '@import "yasb_wallpaper_colors.css";\n.yasb-bar { border: none; }\n')

    processor = CSSProcessor(styles)
    css = processor.process()

    assert "background-color: #1a2b3c;" in css
    assert "@import" not in css
    assert os.path.getsize(palette_path) > 0
