"""Tests for the get_stylesheet() palette hook, running the real core.config.

core.config pulls in the alert dialog, which hard-depends on Windows user32
bindings at import time. On non-Windows we stub that single module so the rest
of the pipeline (settings paths, CSSProcessor, the palette append) runs for
real; on Windows the genuine module is used.
"""

import sys

import pytest

pytest.importorskip("PyQt6.QtWidgets", reason="core.config imports PyQt6")

if sys.platform != "win32":
    sys.modules.setdefault(
        "core.utils.win32.backdrop",
        type(sys)("core.utils.win32.backdrop"),
    )
    sys.modules["core.utils.win32.backdrop"].enable_dwm_frame = lambda *args, **kwargs: None

from core.config import get_stylesheet  # noqa: E402
from core.utils import wallpaper_palette  # noqa: E402

PALETTE_CSS = (
    "/* This file is automatically generated by YASB wallpaper watcher */\n"
    ":root {\n"
    "    --wallpaper-color-1: #1a2b3c;\n"
    "}\n"
    "\n"
    ".yasb-bar {\n"
    "    background-color: #1a2b3c;\n"
    "}\n"
)


@pytest.fixture
def config_home(tmp_path, monkeypatch):
    monkeypatch.setattr("core.config.HOME_CONFIGURATION_DIR", str(tmp_path))
    monkeypatch.setattr("core.config.HOME_STYLES_PATH", str(tmp_path / "styles.css"))
    monkeypatch.setattr("core.config.HOME_CONFIG_PATH", str(tmp_path / "config.yaml"))
    return tmp_path


def test_hook_appends_palette(config_home, monkeypatch):
    (config_home / "styles.css").write_text(".clock-widget { color: white; }\n", encoding="utf-8")
    monkeypatch.setattr(wallpaper_palette, "load_generated_css", lambda: PALETTE_CSS)

    css = get_stylesheet()

    assert css.startswith(".clock-widget")
    assert "background-color: #1a2b3c;" in css


def test_hook_noop_without_generated_file(config_home, monkeypatch):
    (config_home / "styles.css").write_text(".clock-widget { color: white; }\n", encoding="utf-8")
    monkeypatch.setattr(wallpaper_palette, "load_generated_css", lambda: "")

    css = get_stylesheet()

    assert css == ".clock-widget { color: white; }\n"
