import logging
import os

import winrt.windows.ui.viewmanagement as viewmanagement
from PyQt6.QtWidgets import QApplication

from settings import DEFAULT_CONFIG_DIRECTORY

logger = logging.getLogger("system_colors")


class SystemColorsService:
    _instance = None

    @classmethod
    def start_service(cls) -> None:
        if cls._instance is None:
            cls._instance = cls()
            cls._instance.start()

    @classmethod
    def stop_service(cls) -> None:
        if cls._instance is not None:
            cls._instance.stop()
            cls._instance = None

    def __init__(self):
        self._settings = viewmanagement.UISettings()
        self._token = None
        self._css_path = os.path.join(DEFAULT_CONFIG_DIRECTORY, "yasb_colors.css")

        self._colors_to_fetch = []
        color_names = [
            "ACCENT",
            "ACCENT_DARK1",
            "ACCENT_DARK2",
            "ACCENT_DARK3",
            "ACCENT_LIGHT1",
            "ACCENT_LIGHT2",
            "ACCENT_LIGHT3",
            "BACKGROUND",
            "FOREGROUND",
        ]

        for name in color_names:
            try:
                enum_val = getattr(viewmanagement.UIColorType, name)
                var_name = f"--yasb-{name.lower().replace('_', '-')}"
                self._colors_to_fetch.append((name, enum_val, var_name))
            except AttributeError:
                logger.warning("Color type %s is not supported by this OS", name)

        # Ensure the CSS file is written on startup
        self._generate_css()

    def start(self):
        if self._token is None:
            self._token = self._settings.add_color_values_changed(self._on_color_values_changed)
            logger.info("System Colors Service started.")

            app_inst = QApplication.instance()
            if app_inst:
                app_inst.aboutToQuit.connect(self.stop)

    def stop(self):
        if self._token is not None:
            self._settings.remove_color_values_changed(self._token)
            self._token = None
            logger.info("System Colors Service stopped.")

    def _on_color_values_changed(self, sender, args):
        self._generate_css()

    def _generate_css(self):
        try:
            css_lines = [
                "/* This file is automatically generated by YASB */",
                "/* Please import this file in your styles.css */",
                ":root {",
            ]

            for name, enum_val, var_name in self._colors_to_fetch:
                try:
                    color = self._settings.get_color_value(enum_val)
                    css_lines.append(f"    {var_name}: rgb({color.r}, {color.g}, {color.b});")
                    css_lines.append(f"    {var_name}-rgb: {color.r}, {color.g}, {color.b};")
                except Exception as e:
                    logger.warning("Failed to retrieve system color %s: %s", name, e)

            css_lines.append("}")

            with open(self._css_path, "w", encoding="utf-8") as f:
                f.write("\n".join(css_lines) + "\n")

        except Exception as e:
            logger.error("Failed to generate system colors CSS: %s", e)
