"""Wallpaper palette extraction.

Pure image-processing helpers behind the wallpaper watcher feature: they pull
the dominant colors out of an image and turn them into the CSS that recolors
the bar. Everything here is deliberately free of Qt and Windows imports so it
can be unit-tested (and reused) anywhere.

The palette is three colors ranked by pixel count:

  * color-1 is the dominant color, the one the bar background uses when
    auto-apply is on. From it, --wallpaper-text picks white or near-black
    by luminance, so widgets stay readable over it.
  * --wallpaper-accent is the most "vivid" of the three, weighted by how much
    of the image it covers, for highlights and borders.
"""

import colorsys
import logging
import os

from PIL import Image

# Sampling beyond this adds nothing but cost; 128px is plenty for 3 clusters.
_THUMBNAIL_SIZE = (128, 128)

# Luminance above which text over the dominant color should go dark.
_LIGHT_TEXT_THRESHOLD = 0.55


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    """*rgb* as a lowercase #rrggbb string."""
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def extract_palette(image_path: str, max_colors: int = 3) -> list[tuple[int, int, int]]:
    """Extract up to *max_colors* dominant RGB colors from an image, ranked by coverage.

    Raises whatever Pillow raises on unreadable images; callers are expected to
    log and keep the previous palette.
    """
    with Image.open(image_path) as image:
        thumbnail = image.convert("RGB")
        thumbnail.thumbnail(_THUMBNAIL_SIZE)
        quantized = thumbnail.quantize(colors=max_colors, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)

    # quantize() returns an indexed image; the palette holds the RGB values and
    # the pixels only tell us which entry each one landed in. The histogram of a
    # palette-mode image is the count of each palette index, which is what ranks
    # the colors, and only entries actually used end up in the result, which is
    # why a flat-color image yields fewer than three.
    histogram = quantized.histogram()
    palette = quantized.getpalette() or []

    colors: list[tuple[int, int, int]] = []
    ranked = sorted(
        ((index, count) for index, count in enumerate(histogram) if count),
        key=lambda item: item[1],
        reverse=True,
    )
    for index, _count in ranked:
        entry = palette[index * 3 : index * 3 + 3]
        if len(entry) < 3:
            continue
        colors.append((int(entry[0]), int(entry[1]), int(entry[2])))
        if len(colors) == max_colors:
            break
    return colors


def pick_accent(colors: list[tuple[int, int, int]]) -> tuple[int, int, int]:
    """The most vivid of *colors*, weighted toward ones the image actually uses.

    Saturation alone would crown a tiny but loud sliver of the image; the
    brightness half-weight keeps near-black and near-white from scoring well
    while letting a genuinely rich color win even if it is not the dominant one.
    """
    if not colors:
        return (255, 255, 255)

    def vividness(rgb: tuple[int, int, int]) -> float:
        _, saturation, value = colorsys.rgb_to_hsv(*(channel / 255 for channel in rgb))
        return saturation * (0.5 + value / 2)

    return max(colors, key=vividness)


def pick_text(background: tuple[int, int, int]) -> tuple[int, int, int]:
    """Readable text color over *background*: near-white or near-black."""
    r, g, b = background
    luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255
    return (17, 17, 17) if luminance >= _LIGHT_TEXT_THRESHOLD else (255, 255, 255)


def build_css(colors: list[tuple[int, int, int]], auto_apply: bool = True) -> str:
    """The generated stylesheet for *colors*.

    Literal hex values only: YASB resolves var() references in Python before Qt
    ever sees the stylesheet, so the bar picks these up without any variable
    machinery, and users can import the file into their own styles.css too.
    """
    if not colors:
        raise ValueError("Cannot build wallpaper CSS without at least one color")

    accent = pick_accent(colors)
    text = pick_text(colors[0])

    lines = [
        "/* This file is automatically generated by YASB wallpaper watcher */",
        "/* It is regenerated whenever the desktop wallpaper changes */",
        ":root {",
    ]
    for position, rgb in enumerate(colors, start=1):
        r, g, b = rgb
        lines.append(f"    --wallpaper-color-{position}: {rgb_to_hex(rgb)};")
        lines.append(f"    --wallpaper-color-{position}-rgb: {r}, {g}, {b};")
    lines.append(f"    --wallpaper-accent: {rgb_to_hex(accent)};")
    lines.append(f"    --wallpaper-text: {rgb_to_hex(text)};")
    lines.append("}")

    if auto_apply:
        lines += [
            "",
            "/* Auto-apply: recolor the bar from the wallpaper palette */",
            ".yasb-bar {",
            f"    background-color: {rgb_to_hex(colors[0])};",
            f"    color: {rgb_to_hex(text)};",
            "}",
        ]

    return "\n".join(lines) + "\n"


def write_palette_css(path: str, css: str) -> bool:
    """Write *css* to *path* atomically, so a reader never sees a partial file.

    The stylesheet is re-read while the bar is live, so replace-in-place (never
    truncate-in-place) is what keeps a wallpaper change from flashing the bar
    unstyled.
    """
    temp_path = f"{path}.tmp"
    try:
        with open(temp_path, "w", encoding="utf-8") as file:
            file.write(css)
        os.replace(temp_path, path)
        return True
    except OSError:
        logging.exception("Failed to write wallpaper palette CSS to %s", path)
        try:
            os.remove(temp_path)
        except OSError:
            pass
        return False
