"""win32 constants that are missing from win32con"""

import ctypes
from enum import IntEnum

# System error codes
ERROR_SUCCESS = 0
ACCESS_DENIED = 5
ERROR_NOT_FOUND = 0x490

# FormatMessage constants
FORMAT_MESSAGE_FROM_SYSTEM = 0x00001000
FORMAT_MESSAGE_IGNORE_INSERTS = 0x00000200

NIM_ADD = 0x0
NIM_MODIFY = 0x1
NIM_DELETE = 0x2
NIM_SETFOCUS = 0x3
NIM_SETVERSION = 0x4

NIF_MESSAGE = 0x1
NIF_ICON = 0x2
NIF_TIP = 0x4
NIF_STATE = 0x8
NIF_INFO = 0x10
NIF_GUID = 0x20
NIF_REALTIME = 0x40
NIF_SHOWTIP = 0x80

NIN_POPUPOPEN = 0x406
NIN_POPUPCLOSE = 0x407
NIN_SELECT = 0x400
NIN_CONTEXTMENU = 0x7B

INVALID_HANDLE_VALUE = ctypes.c_void_p(-1).value

# Constants for locale information
LOCALE_NAME_MAX_LENGTH = 85
LOCALE_SISO639LANGNAME = 0x59
LOCALE_SISO639LANGNAME2 = 0x67
LOCALE_SISO3166CTRYNAME = 0x5A
LOCALE_SLANGUAGE = 0x2
LOCALE_SCOUNTRY = 0x6
LOCALE_SNAME = 0x5C
LOCALE_SNATIVECTRYNAME = 0x07
LOCALE_SNATIVELANGNAME = 0x04
LOCALE_SABBREVLANGNAME = 0x3

# WiFi constants
WLAN_INTERFACE_STATE_CONNECTED = 1
WLAN_INTF_OPCODE_CURRENT_CONNECTION = 7

ERROR_NDIS_DOT11_POWER_STATE_INVALID = 0x80342002

WLAN_AVAILABLE_NETWORK_CONNECTED = 0x1
WLAN_AVAILABLE_NETWORK_HAS_PROFILE = 0x2

WLAN_NOTIFICATION_SOURCE_NONE = 0x0
WLAN_NOTIFICATION_SOURCE_ACM = 0x8
WLAN_NOTIFICATION_SOURCE_ALL = 0xFFFF

DOT11_AUTH_ALGO_80211_OPEN = 1
DOT11_AUTH_ALGO_RSNA_PSK = 7
DOT11_AUTH_ALGO_WPA3_SAE = 9

DOT11_BSS_TYPE_INFRASTRUCTURE = 1


class WlanNotificationAcm(IntEnum):
    """WLAN Auto Configuration Manager (ACM) notification codes"""

    AUTOCONF_ENABLED = 0x1
    AUTOCONF_DISABLED = 0x2
    BACKGROUND_SCAN_ENABLED = 0x3
    BACKGROUND_SCAN_DISABLED = 0x4
    BSS_TYPE_CHANGE = 0x5
    POWER_SETTING_CHANGE = 0x6
    SCAN_COMPLETE = 0x7
    SCAN_FAIL = 0x8
    CONNECTION_START = 0x9
    CONNECTION_COMPLETE = 0xA
    CONNECTION_ATTEMPT_FAIL = 0xB
    FILTER_LIST_CHANGE = 0xC
    INTERFACE_ARRIVAL = 0xD
    INTERFACE_REMOVAL = 0xE
    PROFILE_CHANGE = 0xF
    PROFILE_NAME_CHANGE = 0x10
    PROFILES_EXHAUSTED = 0x11
    NETWORK_NOT_AVAILABLE = 0x12
    NETWORK_AVAILABLE = 0x13
    DISCONNECTING = 0x14
    DISCONNECTED = 0x15
    ADHOC_NETWORK_STATE_CHANGE = 0x16
    PROFILE_UNBLOCKED = 0x17
    SCREEN_POWER_CHANGE = 0x18
    PROFILE_BLOCKED = 0x19
    SCAN_LIST_REFRESH = 0x1A
