"""
Default root and bar configuration and stylesheet for the YASB Setup Wizard.
"""

CONFIG_HEADER = (
    "# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json\n"
    "\n"
    "# Configuration generated by YASB Setup Wizard.\n"
    "# For more information, visit https://github.com/amnweb/yasb/wiki\n"
)

ROOT_CONFIG: dict = {
    "watch_stylesheet": True,
    "watch_config": True,
    "debug": False,
    "update_check": True,
}

ROOT_BAR: dict = {
    "enabled": True,
    "screens": ["*"],
    "class_name": "yasb-bar",
    "alignment": {
        "position": "top",
        "center": False,
    },
    "animation": {
        "enabled": True,
        "duration": 300,
    },
    "blur_effect": {
        "enabled": True,
        "round_corners": False,
    },
    "window_flags": {
        "always_on_top": False,
        "windows_app_bar": True,
    },
    "dimensions": {
        "width": "100%",
        "height": 34,
    },
    "padding": {
        "top": 0,
        "left": 0,
        "bottom": 0,
        "right": 0,
    },
}

ROOT_STYLE: str = """\
/*
  Stylesheet generated by YASB Setup Wizard.
  For more information, visit https://github.com/amnweb/yasb/wiki
*/

/* Root Variables */
:root {
    --yasb-bar-bg: rgba(36, 36, 36, 0.60);
    --yasb-surface-alt: rgb(61, 61, 61);
    --yasb-bar-border: #303030;
    --yasb-popup-bg: rgba(36, 36, 36, 0.60);
    --yasb-dialog-bg: rgb(43, 43, 43);
    --yasb-dialog-surface: rgb(32, 32, 32);
    --yasb-white-alpha-03: rgba(255, 255, 255, 0.03);
    --yasb-white-alpha-04: rgba(255, 255, 255, 0.04);
    --yasb-white-alpha-05: rgba(255, 255, 255, 0.05);
    --yasb-white-alpha-06: rgba(255, 255, 255, 0.06);
    --yasb-white-alpha-07: rgba(255, 255, 255, 0.07);
    --yasb-white-alpha-08: rgba(255, 255, 255, 0.08);
    --yasb-white-alpha-10: rgba(255, 255, 255, 0.1);
    --yasb-white-alpha-15: rgba(255, 255, 255, 0.15);
    --yasb-white-alpha-20: rgba(255, 255, 255, 0.2);
    --yasb-white-alpha-30: rgba(255, 255, 255, 0.3);
    --yasb-white-alpha-40: rgba(255, 255, 255, 0.4);
    --yasb-white-alpha-70: rgba(255, 255, 255, 0.7);
    --yasb-white-alpha-80: rgba(255, 255, 255, 0.8);
    --yasb-white-alpha-85: rgba(255, 255, 255, 0.85);
    --yasb-fg: rgba(255, 255, 255, 0.9);
    --yasb-fg-muted: rgb(134, 134, 134);
    --yasb-icon-fg: rgba(255, 255, 255, 0.9);
    --yasb-tooltip-bg: rgba(31, 31, 31, 0.95);
    --yasb-tooltip-border: rgb(44, 44, 44);
    --yasb-accent: #4cc2ff;
    --yasb-accent-hover: #40ace2;
    --yasb-accent-fg: #000000;
    --icons-font: "Segoe Fluent Icons";
    --icons-font-fallback: "JetBrainsMono NFP", "JetBrainsMono Nerd Font Propo";
    --system-font: "Segoe UI Variable", "Segoe UI";
}

/* Global Defaults */
* {
    font-size: 12px;
    font-weight: 400;
    font-family: var(--system-font);
    color: var(--yasb-fg);
}

/* Bar */
.yasb-bar {
    background-color: var(--yasb-bar-bg);
    padding: 0px 12px
}

/* Tooltip */
.tooltip {
    background-color: var(--yasb-tooltip-bg);
    border-radius: 4px;
    color: var(--yasb-fg);
    padding: 5px 10px;
    font-size: 12px;
    font-family: var(--system-font);
    font-weight: 600;
    margin-top: 4px;
    border:1px solid var(--yasb-tooltip-border);
}

/* Context Menu */
.context-menu,
.context-menu .menu-checkbox {
    background-color: var(--yasb-bar-bg);
    padding: 4px 0px;
    font-family: var(--system-font);
    font-weight: 600;
    font-size: 12px;
    color: var(--yasb-fg);
}
.context-menu {
    border-radius: 8px;
    border: 1px solid var(--yasb-white-alpha-07);
}
.context-menu::right-arrow {
    width: 8px;
    height: 8px;
    padding-right: 24px;
}
.context-menu::item,
.context-menu .menu-checkbox {
    background-color: transparent;
    padding: 6px 12px;
    margin: 2px 6px;
    border-radius: 6px;
    min-width: 100px;
}
.context-menu::item:selected,
.context-menu .menu-checkbox:hover {
    background-color: var(--yasb-white-alpha-10);
    color: #FFFFFF;
}
.context-menu::separator {
    height: 1px;
    background-color: #404040;
    margin: 4px 8px;
}
.context-menu::item:disabled {
    color: #666666;
    background-color: transparent;
}
.context-menu .menu-checkbox .checkbox {
    border: none;
    padding: 8px 16px;
    font-size: 12px;
    margin: 0;
    color: var(--yasb-fg);
    font-family: var(--system-font);
    font-weight: 600;
}
.context-menu .submenu::item:disabled {
    margin: 0;
    padding-left: 16px;
}
.context-menu .menu-checkbox .checkbox:unchecked {
    color: var(--yasb-fg);
}
.context-menu .menu-checkbox .checkbox::indicator {
    width: 12px;
    height: 12px;
    margin-left: 0px;
    margin-right: 8px;
}
.context-menu .menu-checkbox .checkbox::indicator:unchecked {
    background: #444444;
    border-radius: 2px;
}
.context-menu .menu-checkbox .checkbox::indicator:checked {
    background: #4a90e2;
    border-radius: 2px;
}
.context-menu .menu-checkbox .checkbox:focus {
    outline: none;
}

/* Base Widget Styles */
.widget {
    padding: 0px 6px;
    margin: 4px 0;
    border-radius: 4px;
}

.widget .icon {
    font-size: 16px;
    font-weight: 400;
    color: var(--yasb-icon-fg);
    font-family: var(--icons-font);
}

.widget .label {
    color: var(--yasb-fg);
    font-weight: 600;
    padding-bottom: 2px;
}"""
